using Dapper;

namespace Customer.Api.Database;

public static class DatabaseExtensions
{
    public static void Seed(this IApplicationBuilder app)
    {
        using var scope = app.ApplicationServices.CreateScope();
        var services = scope.ServiceProvider;
        try
        {
            var connectionFactory = services.GetRequiredService<IDbConnectionFactory>();
            using var connection = connectionFactory.CreateConnection();
            
            var createTableScript = @"
CREATE TABLE IF NOT EXISTS public.""Customers""
(
    ""Id""        BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT ""PK_Customers""
            PRIMARY KEY,
    ""FirstName"" TEXT,
    ""LastName""  TEXT
);

ALTER TABLE public.""Customers""
    OWNER TO postgres;
";

            connection.Execute(createTableScript);

            var query = @"select * from ""Customers""";
            var customers = connection.Query<Customer>(query);
            if (customers.ToArray().Any())
                return;
            
            var testCustomer = new Customer()
            {
                FirstName = "Petr",
                LastName = "Ivanov"
            };
            
            var sqlQuery = @"insert into ""Customers"" (""FirstName"", ""LastName"") VALUES (@FirstName, @LastName);";

            connection.Query<int>(sqlQuery, testCustomer);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}